### ISSUE TITLE
Boton responder no se modifica

### ISSUE THREAD

**Issue by jbonet** [pdp-devs/fc-material-design#8]
El selector parece que no funciona correctamente.

```css
   /* Responder */
    a[href^="newreply.php?do=newreply&noquote="] > img {
        display: none;
    }
```
